insert into CLATable values ('1', 'qwe1', null);
insert into CLATable values ('2', 'qwe2', null);
insert into CLATable values ('3', 'qwe3', null);
insert into CLATable values ('4', 'qwe4', null);
insert into CLATable values ('5', 'qwe5', null);
insert into CLATable values ('6', 'qwe6', null);
insert into CLATable values ('7', 'qwe7', null);
insert into CLATable values ('8', 'qwe8', null);
insert into CLATable values ('9', 'qwe9', null);